[phases.setup]
nixpkgs = ["python311Full", "nodejs_18"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm install"
]

[start]
cmd = "node index.js"
